### ISSUE TITLE
Default Config

### ISSUE THREAD

**Issue by storopoli** [storopoli/dead-man-switch#9]
We need to have a better default `Config` than the blanket derived `Default` trait.
Something like:

```toml
username = "me@example.com"
password = ""
smtp_server = "smtp.example.com"
smtp_port = 587
message = "I'm probably dead, go to Central Park NY under bench #137 you'll find an age-encrypted drive. Password is our favorite music in Pascal case"
subject = "[URGENT] Something Happened to Me!"
to = "someone@example.com"
from = "me@example.com"
timer_warning = 0
timer_dead_man = 0
```
